
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:doubao:doubao@tcp(127.0.0.1:5431)/doubao-speech-service"
        descriptionTag: true
        withTime: true
        gJsonSupport: true