
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "sqlite::@file(/Users/nickwilde/Repo/Doubao-Speech-Service/db.sqlite3)"
        descriptionTag: true
        tablesEx: sqlite_sequence
        withTime: true
        gJsonSupport: true
        fieldMapping:
          transcription.updated_at:
            type: "*gtime.Time"
            import: github.com/gogf/gf/v2/os/gtime
          transcription.created_at:
            type: "*gtime.Time"
            import: github.com/gogf/gf/v2/os/gtime
