
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:doubao:doubao@tcp(127.0.0.1:5431)/doubao-speech-service"
        descriptionTag: true
        withTime: true
        gJsonSupport: true
  
  build:
    name: doubao-speech-service
    path: ./bin
    arch: "amd64,arm64"
    system: "darwin,linux,windows"
    packSrc: manifest/config
    packDst: internal/packed/config.go
    version: 1.0.0
    extra: "-ldflags=\"-w -s\""
    exitWhenError: true